#!/bin/sh

set -e

update-alternatives --install /usr/sbin/apt apt /usr/bin/apt 200 || true
update-alternatives --install /usr/sbin/apt apt /usr/bin/io.elementary.apt-shim 900

update-alternatives --install /usr/sbin/apt-get apt-get /usr/bin/apt-get 200 || true
update-alternatives --install /usr/sbin/apt-get apt-get /usr/bin/io.elementary.apt-shim 900

#DEBHELPER#

exit 0
