#!/bin/sh

set -e

update-alternatives --remove apt /usr/bin/io.elementary.apt-shim || true
update-alternatives --remove apt /usr/bin/apt || true

update-alternatives --remove apt-get /usr/bin/io.elementary.apt-shim || true
update-alternatives --remove apt-get /usr/bin/apt-get || true

#DEBHELPER#

exit 0
